/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-126086-ge5ecfe8970-20260812"
#endif /* AVUTIL_FFVERSION_H */
